version: '3'
services:
  study:
    container_name: study
    build: .
    depends_on:
      - mongodb
      - redis
    stdin_open: true
    tty: true
    environment:
      HOST_USER_ID:
      HOST_GROUP_ID:
      HOST_USER_NAME:
      HOST_GROUP_NAME:
    volumes:
      - ../:/study

  redis:
    image: 'redis'
    restart: always
    ports:
      - '6379:6379'

  mongodb:
    image: 'mongo'
    restart: always
    ports:
      - '27017:27017'
